[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
atom_syndication_format = { path = "../"}

[dev-dependencies]
criterion = { version = "0.5" }

[[bench]]
name = "escape_benchmark"
harness = false
